linters:
  enable:
    - govet
    - revive
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - copyloopvar
    - gosimple
    - errname
    - gocheckcompilerdirectives 
    - wrapcheck
    - promlinter
    - prealloc

issues:
  exclude-dirs:
    - test
    - pkg/proto